### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by Jrojro728** [FledgeXu/NeutrinoSourceCode#1]
在你的mod教程的8.1时你不确定的函数：func_230044_c_ 在forge论坛中的一个帖子中用来解决了Gui的照明问题这是否可以这个函数是控制照明的呢？我也只是刚刚做mod不太懂，希望可以改一下。

附链接：[forge论坛](https://forums.minecraftforge.net/topic/96494-solved1152-render-as-2d-icon-in-gui-3d-model-in-hand/#comment-440092) （在这个贴子的最后）

**Comment by FledgeXu** [comment]
看起来可以，但是我没有具体试过……
但是我目前没什么改的动力。

**Comment by Jrojro728** [comment]
那行吧，也没有什么
